apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow-user-example-com
  name: train-api-stop-experiment
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: acc
  algorithm:
    algorithmName: random
  parallelTrialCount: 1
  maxTrialCount: 1
  maxFailedTrialCount: 1
  parameters: 
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.03"
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: seniorcl13/train-api-stop:v1
                command:
                  - "python3"
                  - "main.py"
                  - "--lr=${trialParameters.learningRate}"
            restartPolicy: Never